language: node_js
node_js:
- 8
notifications:
  email:
    recipients:
    - abutterworth@edx.org
    on_success: never
    on_failure: always
install:
  - npm install
script:
- npm run lint
- npm run build
after_success:
- npm run semantic-release
env:
  global:
    # NPM_TOKEN
    - secure: T2YtAlyBcPuc9+KmsMTXI4E/kKEQmNXCLC7wgqlH81tPwtpsoUnkzWfNCAGk5YEgY/VOnFgAU2vINn8WtCqRbvX9WPP50J3kcwREtSusyGZ/dtXtoXw0il8LlOJ4ol99gUKW46SnC9z8pkBKTyENZKk5afW73GGB7+hqSLnm2n5Ls8m993Hsh1aTJXm4ZqlORU2Avlk3Ttrx1mdcz08snzEzjkBj4KViRXgNAuyZycXhmLL4NrtxSVurpBHTfXffcWywuZJ0Euie1q3IdXB4sLf7OMyg1ZoiOuql7Q05eEnY7stGHHKfUPWzlrkFHxBvzM6yB0bvf0nNCAb4FV0eWvn3VcL1wgLNjNJiO0cGnpwkzMybDIZebfqGUuA25CBCbcAPEWbxioUNrID+1KAajQvS3HScG6z8rjrf01NoDZ5g9fynnHGUN0ivlVOoI4aYCndmtYu+qhf8yFW3w8JMk7gd7EJHiq7IeToz871IpDZbqxUGOx4KyJQhxOsWpMiW0Sqvbq1rS9ExCnZ7FI/5/dZCb2wgbkMubwbahJnNJTZRqag85VY3gr2wNlGvy+DdL1nJzD2ZJzf/tZjnAshtVwW/lokgP+lrM/FtblLNY+eGbMhWJHb7tRD6yk7cP/A+K+k9fyVX8HmVPnMfzY3E+z9Iyj/3bKy4Nn4ilpiOzjk=
    # GH_TOKEN
    - secure: mcaptZElUzMCyzo2ll4lRmcuCbqN+S/rLU0AkM3IxAw40dbPI1fFtGtKZA5EIgCu+S8MX06fzlJ15eF8vWP1d/kAUp6hBws4c9yF5M3PGhKqPSZLys5lLGq4+sWv6IyU/X9WaWiQsvt8BomnKlWhlQu0Po5f0ckDVo/36A69cxUSvII9sGZsJC82CoaaP/6672QlxXXOBepCD+OtIrQq2PGU4W41YX2uhVIxGbdxdKj/+KWbO63rdrbKcVH2gVB7NKtLHEcCDD+7GKn1yH+C6KINaa3cDZQo3q91Cv7RcjvdOL1L+j5dmiVmZRNX1QngVMGRcgsdWHhs8L/5B39e1ksnes60eeQtL6u5RhNyAylyvfN/cVaCC+DRYwpr9SFPQ51YK40BKULC7fueSOXMR1OGRXNEjRaL694vJ7KjCg4GOuxf+DZcFyABQvABcUEwKj4ayn/vWCUSyTly0VgSOxxQLtqj5WObj3asrsCAwQUJ0jAXsFP7WAAzJSheb5R1kHAkTtqp4gcn8miuujCEp4kMw6YfvmwWUb5ZrSP72QxQ3retdrPfokaThcfxfGFnzfVCOoD4DEaWTxLbPKyPcYYnpskfgEmbHiR44qEfUL/lAqBncqUgo4A02GUpCajPzOqA1vpvfE9DT8oMw4Kk37SIAKNao225EgBU3j45qDM=
